### ISSUE TITLE
esri-example slurp, problem with css

### ISSUE THREAD

**Issue by saclarky** [stdavis/dojo-build-presentation#1]
I'm getting stuck running 'slurp_esri_modules.sh' in the esri-example folder. I'm on Windows using Cygwin and when the script gets to retrieving 'css/esri.css' it freezes. I receive a 200OK from the request, but the length returned is unspecified and when it goes to save the css there is a long wait. It then returns with 'error at byte 150382 (no error). Retrying'. If I open the document however, it's all there (I compared it to what was at the actual web address). Have you encountered this before?

**Comment by stdavis** [comment]
No I haven't run into that issue before. I've since abandoned that bash file in favor of: https://github.com/steveoh/grunt-esri-slurp

-Scott

**Comment by saclarky** [comment]
Alrighty, pretty confident it's user error on my part. 'grunt-esri-slurp' worked out for me.

**Comment by stdavis** [comment]
Great!

On Wed, Apr 1, 2015 at 11:06 AM, Sarah Clark notifications@github.com
wrote:

> Alrighty, pretty confident it's user error on my part. 'grunt-esri-slurp'
> worked out for me.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stdavis/dojo-build-presentation/issues/1#issuecomment-88552231
> .

## 

_Scott Davis_
Utah AGRC http://gis.utah.gov/developer/
stdavis@utah.gov
@ScottAGRC https://twitter.com/ScottAGRC
